%% LifeClef 2015 classification framework
%
% Written by Carmine E. Cella, ENS - Paris
% contact: carmine.emanuele.cella@ens.fr
%

%clear all % Warning!!
close all

rng (1);

addpath(genpath('../../libs/scattering.m/'));
addpath('../../libs/ScatNetLight/dimensionality_reduction/');
%addpath('../../libs/libsvm_light'); % Mia Xu Chen
addpath(genpath('../../libs/ScatNetLight/svm_robust/'));
%addpath('../../libs/ScatNetLight/svm_robust/libsvm-compact-0.1/matlab/');

addpath ('../../libs/mfcc');
%addpath ('../../libs/GMM');
%addpath(genpath('../../libs/randomforest-matlab/'));
%addpath(genpath('../../libs/SPKmeans'));
%addpath ('../HSC');

%% parameters and structures
%db_params = struct ('location', '../../datasets/Instrument_samples');            % 94 classes
%db_params = struct ('location', '../../datasets/Mogees_april_2015');            % 6 classes

%db_params = struct ('location', '../../datasets/bird_fake');                   % 2 classes
db_params = struct ('location', '../../datasets/minibird');                    % 15 classes
%db_params = struct ('location', '../../datasets/BD50CLASSES/FOLDERS');         % 50 classes
%db_params = struct ('location', '../../datasets/BirdCLEF_2014_folders');       % 500 classes

features_params = struct ('type', 'mfcc', ...
    'mfcc_minf', 500, ...
    'mfcc_maxf', 21000, ....
    'mfcc_bands', 40, ...
    'mfcc_ceps', 13, ...
    'mfcc_win', .025, ...
    'mfcc_hop', .025, ...
    'scat_type', 'scat1', ...
    'scat_chunksize', 16384, ...
    'scat_tw1', 2048, ...
    'scat_tw2', 2048, ...
    'scat_Q', 16, ...
    'scat1_max_coeff', 90, ...
    'rms_norm', 'yes', ...
    'log_features', 'no', ...
    'thresholding', 'no', ...
    'debug', 'no');

learning_params = struct ('type', 'none', ...
    'pca_whitening', 'no', ...
    'non_lin', 'module', ...
    'K', 140);

summarization_params = struct ('type', 'mean_std', ...
    'components', 2); % FIXME: must be set accordingly!

equalization_params = struct ('type', 'none');

%%% global parameters
Nfolds = 3;

%% run natch tests changing classification parameters
ntrees = [1:10:51];
fboots = [1:-.1:.1];

results = [];
for i = 1 : length (ntrees)
    for j = 1 : length (fboots)
        classification_params = struct ('type', 'RF', ...
            'tt_ratio', .25, ...
            'dimensions', 0, ...
            'standardize', 'yes', ...
            'structured_validation', 'yes', ...
            'svm_kernel', 'rbf', ...
            'svm_sigma_v', .81, ...
            'svm_C', .1, ...
            'RF_ntree', ntrees(i), ...
            'RF_fboot', fboots(j), ...
            'histogram_voting', 'no',...
            'debug', 'no');
        [~, ~, ~, acc, map, inbag] = LC_batch (db_params, features_params, learning_params, ...
            summarization_params, equalization_params, classification_params, Nfolds);

        fprintf ('ntrees = %d, inbag = %f, map = %f\n', ntrees(i), inbag, map);
        p = [ntrees(i) inbag map];
        results = [results p'];
    end
end

surf (results)
title ('Ntrees vs in-bag vs MAP')
