%% LifeClef 2015 classification framework
%
% Written by Carmine E. Cella, ENS - Paris
% contact: carmine.emanuele.cella@ens.fr
%

%clear all % Warning!!
close all

rng (1);

addpath(genpath('../../libs/scattering.m/'));
addpath('../../libs/ScatNetLight/dimensionality_reduction/');
%addpath('../../libs/libsvm_light'); % Mia Xu Chen
addpath(genpath('../../libs/ScatNetLight/svm_robust/'));
%addpath('../../libs/ScatNetLight/svm_robust/libsvm-compact-0.1/matlab/');

addpath ('../../libs/mfcc');
%addpath ('../../libs/GMM');
%addpath(genpath('../../libs/randomforest-matlab/'));
%addpath(genpath('../../libs/SPKmeans'));
%addpath ('../HSC');

%% parameters and structures
%db_params = struct ('location', '../../datasets/Instrument_samples');            % 94 classes
%db_params = struct ('location', '../../datasets/Mogees_april_2015');            % 6 classes

%db_params = struct ('location', '../../datasets/bird_fake');                   % 2 classes
db_params = struct ('location', '../../datasets/minibird');                    % 15 classes
%db_params = struct ('location', '../../datasets/BD50CLASSES/FOLDERS');         % 50 classes
%db_params = struct ('location', '../../datasets/BirdCLEF_2014_folders');       % 500 classes

features_params = struct ('type', 'mfcc', ...
    'mfcc_minf', 500, ...
    'mfcc_maxf', 16000, ....
    'mfcc_bands', 40, ...
    'mfcc_ceps', 13, ...
    'mfcc_win', .025, ...
    'mfcc_hop', .025, ...
    'scat_type', 'scat1', ...
    'scat_chunksize', 16384, ...
    'scat_tw1', 1024, ...
    'scat_tw2', 1024, ...
    'scat_Q', 16, ...
    'scat_isrenorm', false, ...
    'scat1_max_coeff', 90, ...
    'alogc_win', 1024, ...
    'alogc_olap', 512, ...
    'alogc_nbands', 40, ...
    'alogc_ncoeff', 13, ...
    'alogc_alpha', 3.5, ...
    'rms_norm', 'yes', ...
    'log_features', 'no', ...
    'thresholding', 'no', ...
    'debug', 'no');

learning_params = struct ('type', 'none', ...
    'pca_whitening', 'no', ...
    'non_lin', 'module', ...
    'K', 40);

summarization_params = struct ('type', 'scat_summary', ...
    'components', 10);

equalization_params = struct ('type', 'none');

classification_params = struct ('type', 'RF', ...
    'tt_ratio', .25, ...
    'dimensions', 0, ...
    'standardize', 'yes', ...
    'structured_validation', 'yes', ...
    'svm_kernel', 'rbf', ...
    'svm_sigma_v', 1.1, ...
    'svm_C', 10, ...
    'RF_ntree', 30, ...
    'RF_fboot', 1, ...
    'RF_var2samp', 200, ...
    'histogram_voting', 'no',...
    'debug', 'no');

%%% global parameters
Nfolds = 3;

%% run classifcation
[F, labels, entries, acc, map] = LC_batch (db_params, features_params, learning_params, ...
    summarization_params, equalization_params, classification_params, Nfolds);

%% example for batch execution
% C = [0.1 1 2 4 10 20 50 100];
% sigma = [.8:.1:1.3];
% results = [];
% for i = 1 : length (C)
%     for j = 1 : length (sigma)
%         
%         ....
%         fprintf ('C = %f, sigma = %f, map = %f\n', C(i), sigma(j), map);
%         p = [C(i) sigma(j) map];
%         results = [results p'];
%         
%     end
% end


% eof

%% Show features
imagesc(F);
nExamples_per_class = 15;
nFeatures = 400;
for class_index = 1:15
    x = class_index * nExamples_per_class - 0.5;
    line([x x], [0 nFeatures], 'Color', 'r', 'LineWidth', 2);
    drawnow();
end